### ISSUE TITLE
`new: true`?

### ISSUE THREAD

**Issue by Martin-Pitt** [diegoddox/react-notification-center#1]
Loving the notification center, exactly what I was looking for!

However I noticed that the "new" appears to work to the opposite of what it means. It's more like "old".

E.g. when I set `new: true`, then the notification is marked as if it has been read already.
When I set `new: false`, the `new` class is added to the notification and it is marked as unread.

**Comment by diegoddox** [comment]
@Martin-Pitt Thanks a lot, I'm glad that you find useful.
I have fix this issue, just update to the new version and you're read to rock.
